# Generated by Django 4.0.3 on 2022-04-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower_documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disbursment_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='extra_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='', max_length=50)),
                ('lga', models.CharField(default='', max_length=150)),
                ('Nearest_landmark', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='male', max_length=10)),
                ('marital_status', models.CharField(default='Married', max_length=100)),
                ('education', models.CharField(default='', max_length=100)),
                ('employment_status', models.BooleanField(default='False')),
                ('sector', models.CharField(default='', max_length=100)),
                ('monthly_income', models.FloatField(default=0.0)),
                ('registered_company', models.BooleanField(default='False')),
                ('cac', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_disbursed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursment_id', models.IntegerField(default=0)),
                ('borrower', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bvn', models.CharField(max_length=20)),
                ('loan_product_name', models.CharField(default='', max_length=20)),
                ('loan_amount', models.FloatField(default=0.0)),
                ('interest', models.FloatField(default=0.0)),
                ('amount_disbursed', models.FloatField(default=0.0)),
                ('amount_due', models.FloatField(default=0.0)),
                ('princpal_due', models.FloatField(default=0.0)),
                ('interest_due', models.FloatField(default=0.0)),
                ('penalty', models.FloatField(default=0.0)),
                ('tenor', models.CharField(max_length=20)),
                ('interest_rate', models.CharField(max_length=30)),
                ('date_disbursed', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='settled', max_length=20)),
                ('first_payment_due', models.DateField(auto_now=True)),
                ('last_payment_due', models.DateField(auto_now=True)),
                ('loan_classification', models.CharField(default='closed', max_length=30)),
                ('principal_paid', models.FloatField(default=0.0)),
                ('insterest_paid', models.FloatField(default=0.0)),
                ('penalty_paid', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='loan_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Loan_repayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('payment_date', models.DateTimeField()),
                ('is_auto_debit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Returning_good_borrowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_cached_loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist_response', models.CharField(max_length=10)),
                ('credolab_score', models.CharField(max_length=10)),
                ('pengme_response', models.CharField(max_length=20)),
                ('hadada_response', models.CharField(max_length=20)),
                ('loan_offer', models.FloatField(default=0.0)),
                ('is_disbursed', models.BooleanField(default=False)),
            ],
        ),
    ]
