# Generated by Django 4.0.3 on 2022-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan_disbursed',
            new_name='Loans',
        ),
    ]
